version: '3'

services:
  db:
    image:
      postgres:10.6-alpine
    environment:
      - POSTGRES_PASSWORD=123456

  app:
    build:
      args:
        - USER_NAME=${USER}
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - DJANGO_SETTINGS_MODULE=todolistapi.settings.test
    volumes:
      - ${PWD}/src:/app
    ports:
      - 8000:8000
    depends_on:
      - db