FROM alpine:latest

ENV TERRAFORM_VERSION=0.11.11

RUN apk update && \
    apk add --no-cache git && \
    wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -q -O terraform.zip && \
    unzip terraform.zip -d /usr/local/bin && \
    rm -f terraform.zip && \
    chmod +x /usr/local/bin/terraform